# Generated by Django 3.1.2 on 2023-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230504_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='db_producto',
        ),
    ]
