# Generated by Django 3.1.2 on 2023-05-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_carrito'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item_carrito',
            table='db_item_carrito',
        ),
    ]
