# Generated by Django 3.1.2 on 2023-05-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230520_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('nom_sus', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('suscripcion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'db_suscripcion',
            },
        ),
    ]
