# Generated by Django 3.1.2 on 2023-05-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_suscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='suscripcion',
            new_name='suscripcion_check',
        ),
    ]
